/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface VotingInterface extends Interface {
    getFunction(nameOrSignature: "Status" | "authorize" | "desauthorize" | "getWinner" | "number_of_Proposals" | "owner" | "proposals" | "proposals_Activation" | "proposals_Desactivation" | "propositions" | "renounceOwnership" | "totalProposals" | "transferOwnership" | "vote_Activation" | "vote_Choice" | "vote_Desactivation" | "winningProposalId"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "ProposalRegistered" | "Voted" | "VoterRegistered" | "WorkflowStatusChange"): EventFragment;

    encodeFunctionData(functionFragment: 'Status', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorize', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'desauthorize', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getWinner', values?: undefined): string;
encodeFunctionData(functionFragment: 'number_of_Proposals', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'proposals_Activation', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposals_Desactivation', values?: undefined): string;
encodeFunctionData(functionFragment: 'propositions', values: [string]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalProposals', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote_Activation', values?: undefined): string;
encodeFunctionData(functionFragment: 'vote_Choice', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote_Desactivation', values?: undefined): string;
encodeFunctionData(functionFragment: 'winningProposalId', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'Status', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'desauthorize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWinner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'number_of_Proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals_Activation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposals_Desactivation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propositions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalProposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote_Activation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote_Choice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote_Desactivation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'winningProposalId', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProposalRegisteredEvent {
      export type InputTuple = [proposalId: BigNumberish];
      export type OutputTuple = [proposalId: bigint];
      export interface OutputObject {proposalId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotedEvent {
      export type InputTuple = [voter: AddressLike, proposalId: BigNumberish];
      export type OutputTuple = [voter: string, proposalId: bigint];
      export interface OutputObject {voter: string, proposalId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoterRegisteredEvent {
      export type InputTuple = [voterAddress: AddressLike];
      export type OutputTuple = [voterAddress: string];
      export interface OutputObject {voterAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkflowStatusChangeEvent {
      export type InputTuple = [previousStatus: BigNumberish, newStatus: BigNumberish];
      export type OutputTuple = [previousStatus: bigint, newStatus: bigint];
      export interface OutputObject {previousStatus: bigint, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Voting extends BaseContract {
    
    connect(runner?: ContractRunner | null): Voting;
    waitForDeployment(): Promise<this>;

    interface: VotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    Status: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    authorize: TypedContractMethod<
      [_addr: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    desauthorize: TypedContractMethod<
      [_addr: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getWinner: TypedContractMethod<
      [],
      [[string, bigint, string]],
      'view'
    >
    

    
    number_of_Proposals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proposals: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint] & {description: string, voteCount: bigint, ProposalId: bigint }],
      'view'
    >
    

    
    proposals_Activation: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    proposals_Desactivation: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    propositions: TypedContractMethod<
      [voteText: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    totalProposals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vote_Activation: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    vote_Choice: TypedContractMethod<
      [_addrProposition: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vote_Desactivation: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    winningProposalId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'Status'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'authorize'): TypedContractMethod<
      [_addr: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'desauthorize'): TypedContractMethod<
      [_addr: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getWinner'): TypedContractMethod<
      [],
      [[string, bigint, string]],
      'view'
    >;
getFunction(nameOrSignature: 'number_of_Proposals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proposals'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint] & {description: string, voteCount: bigint, ProposalId: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'proposals_Activation'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'proposals_Desactivation'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'propositions'): TypedContractMethod<
      [voteText: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalProposals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote_Activation'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote_Choice'): TypedContractMethod<
      [_addrProposition: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote_Desactivation'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'winningProposalId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProposalRegistered'): TypedContractEvent<ProposalRegisteredEvent.InputTuple, ProposalRegisteredEvent.OutputTuple, ProposalRegisteredEvent.OutputObject>;
getEvent(key: 'Voted'): TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
getEvent(key: 'VoterRegistered'): TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;
getEvent(key: 'WorkflowStatusChange'): TypedContractEvent<WorkflowStatusChangeEvent.InputTuple, WorkflowStatusChangeEvent.OutputTuple, WorkflowStatusChangeEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProposalRegistered(uint256)': TypedContractEvent<ProposalRegisteredEvent.InputTuple, ProposalRegisteredEvent.OutputTuple, ProposalRegisteredEvent.OutputObject>;
      ProposalRegistered: TypedContractEvent<ProposalRegisteredEvent.InputTuple, ProposalRegisteredEvent.OutputTuple, ProposalRegisteredEvent.OutputObject>;
    

      'Voted(address,uint256)': TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
      Voted: TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
    

      'VoterRegistered(address)': TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;
      VoterRegistered: TypedContractEvent<VoterRegisteredEvent.InputTuple, VoterRegisteredEvent.OutputTuple, VoterRegisteredEvent.OutputObject>;
    

      'WorkflowStatusChange(uint8,uint8)': TypedContractEvent<WorkflowStatusChangeEvent.InputTuple, WorkflowStatusChangeEvent.OutputTuple, WorkflowStatusChangeEvent.OutputObject>;
      WorkflowStatusChange: TypedContractEvent<WorkflowStatusChangeEvent.InputTuple, WorkflowStatusChangeEvent.OutputTuple, WorkflowStatusChangeEvent.OutputObject>;
    
    };
  }